title: 얼간이 개발자 Gump
description: 얼간이 개발자 Gump

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
#- title: About
   #url: /about
#- title: Contact
   #url: /contact

social:
   #github: kineo2k 
   #twitter: kineo2k 
   #facebook: kineo2k
   email: kineo2k@gmail.com

google_analytics: "UA-115758295-1"
