title: 얼간이 프로그래머 Gump
description: 얼간이 프로그래머 Gump

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
#- title: Contact
   #url: /contact

social:
   #github: kineo2k 
   #twitter: kineo2k 
   #facebook: kineo2k
   email: kineo2k@gmail.com

exclude:
 - README.md
 - LICENSE
 - package.json
 - package-lock.json
 - gulpfile.js 
 - Gemfile
 - Gemfile.lock
 - jekyll_serve.sh

google_analytics: "UA-115758295-1"
